name: Send Discord Webhook Every 30 Minutes

on:
  schedule:
    - cron: "*/30 * * * *"  # 매 30분마다 실행
  workflow_dispatch:        # 수동 실행도 가능

jobs:
  send-webhook:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run webhook script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
          BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
        run: |
          cd .github/workflows
          python webhook.py
